[package]
name = "git_me_the_oldest_line"
version = "0.1.0"
authors = ["iexus <2.-@twopointline.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
chrono = "0.4"
clap = "2.33"
